### ISSUE TITLE
Feature Request: upgrade PettingZoo version

### ISSUE THREAD

**Issue by elliottower** [SonicKurt/Galaga-AI#5]
Hi, I see this is a class project so I'm not sure if this is relevant, but I wanted to post anyways. Would you like this project to be listed in the PettingZoo [third party environments](https://pettingzoo.farama.org/environments/third_party_envs/) list? If so we need projects to be compatible with the most recent version (>=1.20). I can remove your project if it isn't planned to be maintained or it isn't possible to upgrade. Unity ML agents itself [needs to update](https://github.com/Unity-Technologies/ml-agents/issues/5890), so that's probably a big blocker, but just figured I'd reach out and ask if there was any interest in being listed and if they do end up updating, would you be able to update yourself?

The older versions of PettingZoo use OpenAI Gym, which is not maintained as of a few years ago. Gymnasium](https://github.com/Farama-Foundation/Gymnasium) is the maintained fork which can be used as a drop-in replacement.
Gymnasium and PettingZoo are compatible with current RL training libraries ([rllib](https://github.com/ray-project/ray/tree/master/rllib), [tianshou](https://github.com/thu-ml/tianshou) and [CleanRL](https://github.com/vwxyzjn/cleanrl) have already migrated, and [stable-baselines3](https://github.com/DLR-RM/stable-baselines3/blob/e5deeed16efb57c34ccdcb14692439154d970527/docs/guide/install.rst#bleeding-edge-version) will soon) as well as other tools such as Comet and WandB.

For information about upgrading and compatibility, see [migration guide](https://gymnasium.farama.org/content/migration-guide/) and [gym compatibility](https://gymnasium.farama.org/content/gym_compatibility/). The main difference is the API has switched to returning `truncated` and `terminated`, rather than `done`, in order to give more information and mitigate edge case issues.

**Comment by SonicKurt** [comment]
Hi Elliot,

My team is just learning how to use Unity ML-Agents to integrate the reinforcement learning we need to be done on this project. Currently, we are not interested in listing this project for the PettingZoo third-party environments. Thank you for reaching out. Have a good day.

Thank you!
